server:
  port: 8189
  servlet:
    context-path: /app
utils:
  cart:
    prefix: SPRING_WEB_
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
integrations:
  cart-service:
    url:http://localhost:8189/winter-market-cart/
    connect-timeout: 10000
    read-timeout: 5000
    write-timeout: 5000




